name: nf-core test droplet workflow
# This workflow is triggered on PRs opened against the main/master and hackaton branch.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.

on:
  pull_request:
    branches:
      - main
      - master
      - hackathon
  workflow_dispatch:
